---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-tls-secret
  namespace: default
spec:
  secretName: hubble-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - hubble.internal.rayq.app
