apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIPs: true
  ipPools:
    - private-pool
    - public-pool
