apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rayq-wildcard-tls
  namespace: default
spec:
  secretName: rayq-wildcard-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - rayq.app
    - "*.rayq.app"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-secret
  namespace: default
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - argocd.internal.rayq.app
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-tls-secret
  namespace: default
spec:
  secretName: hubble-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - hubble.internal.rayq.app
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-secret
  namespace: default
spec:
  secretName: vault-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - vault.internal.rayq.app
