apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rayq-wildcard-tls
  namespace: default
spec:
  secretName: rayq-wildcard-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - rayq.app
    - "*.rayq.app"
