apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: "10.20.0.1"
  listeners:
    - name: argocd-https
      port: 443
      protocol: HTTPS
      hostname: "argocd.internal.rayq.app"
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-tls-secret
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: hubble-https
      port: 443
      protocol: HTTPS
      hostname: "hubble.internal.rayq.app"
      tls:
        mode: Terminate
        certificateRefs:
          - name: hubble-tls-secret
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: vault-https
      port: 443
      protocol: HTTPS
      hostname: "vault.internal.rayq.app"
      tls:
        mode: Terminate
        certificateRefs:
          - name: vault-tls-secret
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: wildcard-https
      port: 443
      protocol: HTTPS
      hostname: "*.internal.rayq.app"
      tls:
        mode: Terminate
        certificateRefs:
          - name: rayq-wildcard-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
