---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-secret
  namespace: default
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - argocd.internal.rayq.app
