kind: Kustomization
resources:
  - route.yaml
  - namespace.yaml

  - secret.yaml
  - configmap.yaml

  - argocd-application-controller.yaml
  - argocd-applicationset-controller.yaml
  - argocd-dex-server.yaml
  - argocd-metrics.yaml
  - argocd-repo-server.yaml
  - argocd-notification-controller.yaml
  - argocd-server.yaml
  - argocd-redis.yaml

  - https://github.com/argoproj/argo-cd/manifests/crds?ref=stable # external CRDs
