---
- name: Setup Containerd
  hosts:
    - ssh.rayq.app
  become: yes
  roles:
    - containerd
  tags:
    - k8s
    - all
    - containerd

- name: Setup Network
  hosts:
    - ssh.rayq.app
  become: yes
  roles:
    - network
  tags:
    - k8s
    - all
    - network

- name: Setup K8S
  hosts:
    - ssh.rayq.app
  become: yes
  roles:
    - kubeadm
  tags:
    - k8s
    - all
    - kubeadm

- name: Setup WireGuard
  hosts:
    - ssh.rayq.app
  become: yes
  roles:
    - wg
  tags:
    - all
    - wg
