kind: Kustomization
resources:
  - apps.yaml
  - argocd.yaml
  - cilium.yaml
  - kata.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - vault.yaml
  - gateway.yaml
  - system.yaml
  - local-path-provisioner.yaml
