kind: Kustomization
resources:
  - apps.yaml

  # GitOps
  - argocd.yaml

  # Secrets
  - external-secrets.yaml
  - cert-manager.yaml
  - vault.yaml

  # Networking
  - gateway.yaml
  - cilium.yaml

  # System
  - metallb.yaml
  - system.yaml

  # CSI
  - local-path-provisioner.yaml

  # CRI
  - kata.yaml
