apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  labels:
    app: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  destination:
    name: in-cluster
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: v0.13.10
    helm:
      releaseName: metallb
      skipCrds: true
      values: |
        controller:
          enabled: true
          replicaCount: 1
          priorityClassName: "critical-resilient"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true

        speaker:
          enabled: true
          priorityClassName: "system-node-critical"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_RAW

  - repoURL: https://github.com/TheRayquaza/k8s-sandbox.git
    targetRevision: main
    path: k8s/metallb
