---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-secret
  namespace: default
spec:
  secretName: vault-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - vault.internal.rayq.app
