apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - route.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - vault-auth-token.yaml
  - cluster-secret-store.yaml
  - certificate.yaml
#  - network.yaml
