---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls-secret
  namespace: default
spec:
  secretName: immich-tls-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - immich.internal.rayq.app
